import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    settings: 'Settings',
    logout: 'Logout',
    signIn: 'Sign In',
    signUp: 'Create Account',
    signupHeading: 'Create Your Account',
    loginSubheading: 'Smart Agriculture Platform',
    emailAddress: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    minPasswordChars: 'Min. 6 characters',
    noAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    createOne: 'Create one',
    signInLink: 'Sign in',
    bySigningUp: 'By signing up, you agree to our Terms of Service and Privacy Policy',
    freeAccount: 'Free account',
    instantSetup: 'Instant setup',
    fullFeatures: 'Full features',
    language: 'Language',
    languageName: 'English',
    pleaseFillFields: 'Please fill in all fields',
    invalidEmail: 'Invalid email address',
    noAccountFound: 'No account found with this email',
    incorrectPassword: 'Incorrect password',
    emailAlreadyInUse: 'Email already in use',
    weakPassword: 'Password is too weak',
    passwordsDoNotMatch: 'Passwords do not match',
    nameAtLeast2Chars: 'Name must be at least 2 characters',
    passwordAtLeast6Chars: 'Password must be at least 6 characters',
    failedToSignIn: 'Failed to sign in',
    failedToCreateAccount: 'Failed to create account',
    signingIn: 'Signing in...',
    creatingAccount: 'Creating Account...',
    realTimeMonitoring: 'Real-time monitoring',
    aiInsights: 'AI insights',
    smartControls: 'Smart controls',
    emailPlaceholder: 'your.email@company.com',
    passwordPlaceholder: 'Enter your password',
    confirmPasswordPlaceholder: '••••••••',
    dashboardOverview: 'Real-time monitoring of all trays and system health',
    activeTrays: 'Active Trays',
    averageHealth: 'Average Health',
    activeAlerts: 'Active Alerts',
    lastUpdate: 'Last Update',
    traysCurrentlyOnline: 'Trays currently online',
    averageAIScore: 'Average AI score across trays',
    openSystemNotifications: 'Open system notifications',
    mostRecentSensorData: 'Most recent sensor data',
    quickActions: 'Quick Actions',
    jumpIntoWorkflows: 'Jump into the key Farmsense workflows.',
    manageTrays: 'Manage Trays',
    viewAnalytics: 'View Analytics',
    mlInsights: 'ML Insights',
    systemSettings: 'System Settings',
    howToUseFarmsense: 'How to Use Farmsense',
    assignYourTrays: 'Assign your trays to crops in Tray Management.',
    monitorLiveConditions: 'Monitor live conditions and alerts on the Dashboard.',
    trackTrends: 'Track trends and performance in Analytics.',
    reviewAIInsights: 'Review AI insights in ML Insights.',
    adjustPreferences: 'Adjust preferences in Settings.',
    recentAlerts: 'Recent Alerts',
    aiDrivenInsights: 'AI-driven insights',
    exploreMLInsights: 'Explore ML Insights',
    goToMLInsights: 'Go to ML Insights',
    trayStatus: 'Tray Status',
    trayDetails: 'Tray {trayId} Details',
    waitingForSensorData: 'Waiting for sensor data...',
    liveSensorReadings: 'Live Sensor Readings',
    cropLabel: 'Crop',
    statusLabel: 'Status',
    aiScoreLabel: 'AI Score',
    testControls: 'Test Controls',
    simulateTempAnomaly: 'Simulate Temp Anomaly',
    simulateHumidityAnomaly: 'Simulate Humidity Anomaly',
    assign: 'Assign',
    cancel: 'Cancel',
    selectCropPlaceholder: 'Select a crop...',
    trayManagement: 'Tray Management',
    assignCropsDescription: 'Assign crops to trays and monitor parameters',
    yourTrays: 'Your Trays',
    cropProfiles: 'Crop Profiles',
    systemControlsLabel: 'System Controls',
    turnOnLED: 'Turn ON LED',
    turnOnAC: 'Turn ON AC',
    startIrrigation: 'Start Irrigation',
    analyticsAndTrends: 'Analytics & Trends',
    monitorSensorTrends: 'Monitor sensor trends and historical data',
    selectTrayLabel: 'Select Tray',
    timeRangeLabel: 'Time Range',
    last1Hour: 'Last 1 Hour',
    last6Hours: 'Last 6 Hours',
    last12Hours: 'Last 12 Hours',
    last24Hours: 'Last 24 Hours',
    last7Days: 'Last 7 Days',
    currentReadingsHeading: 'Current Readings',
    yieldForecastHeading: 'Yield Forecast',
    harvestProjectionHeading: 'Harvest Projection',
    usingRealSensorHistory: 'Using real sensor history for prediction.',
    usingFallbackTrendData: 'Using fallback trend data for prediction.',
    temperatureTrend: 'Temperature Trend',
    humidityTrend: 'Humidity Trend',
    pHTrend: 'pH Level Trend',
    waterUsageTrend: 'Water Usage Trend',
    noData: 'No data',
    liveSensorReadings: 'Live Sensor Readings',
    temperature: 'Temperature',
    humidity: 'Humidity',
    score: 'Score',
    phLevel: 'pH Level',
    lightHours: 'Light Hours',
    assignToTray: 'Assign to Tray',
    confidence: 'Confidence',
    trendLabel: 'Trend',
    daysToHarvest: 'Days to Harvest',
    estimatedDate: 'Est. Date',
    tbd: 'TBD',
    optimalParametersFor: 'Optimal Parameters for {cropName}',
    maturity: 'Maturity',
    estimatedYield: 'Estimated Yield',
    harvestReadiness: 'Harvest Readiness',
    aiPoweredPredictions: 'AI-powered predictions for optimal farming',
    noTraySelected: 'No tray selected',
    realTrayHistory: 'real tray history',
    fallbackSensorData: 'fallback sensor data',
    efficiencyScore: 'Efficiency Score',
    days: 'days',
    growStageLabel: 'Growth Stage',
    vegetative: 'Vegetative',
    flowering: 'Flowering',
    fruiting: 'Fruiting',
    daysSincePlanted: 'Days Since Planted',
    healthy: 'Healthy',
    yieldPredictionTitle: 'Yield Prediction',
    harvestPredictionTitle: 'Harvest Prediction',
    nutrientRequirements: 'Nutrient Requirements',
    waterConsumptionForecast: 'Water Consumption Forecast',
    predictedDailyUsage: 'Predicted Daily Usage',
    adjustmentFactors: 'Adjustment Factors',
    adjustmentLabel: 'Adjustment',
    reasonLabel: 'Reason',
    resourceEfficiency: 'Resource Efficiency',
    anomalyDetection: 'Anomaly Detection',
    riskLevelLabel: 'Risk Level',
    noAnomaliesDetected: '✅ No anomalies detected. System operating normally.',
    systemOperatingNormally: 'System operating normally.',
    configureSystem: 'Configure your Farmsense system',
    accountSettings: 'Account Settings',
    notificationsHeading: 'Notifications',
    criticalAlerts: 'Critical Alerts',
    dailyReports: 'Daily Reports',
    marketingEmails: 'Marketing Emails',
    dataRefreshInterval: 'Data Refresh Interval (seconds)',
    alertSensitivity: 'Alert Sensitivity',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    saveSettings: 'Save Settings',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    update: 'Update',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    selectCrop: 'Select a crop...',
    tray: 'Tray',
    trayLabel: 'Tray',
    unassigned: 'Unassigned',
    onlineStatus: '🟢 Online',
    offlineStatus: '🔴 Offline',
    hardwareSensorSection: 'Hardware Sensor Interface',
    hardwareSensorHoverDescription: 'Hover a sensor to see live data from the selected tray.',
    arduinoSensor: 'Arduino Board',
    arduinoSensorDesc: 'Main controller board which gathers all tray sensor readings.',
    temperatureSensor: 'Temperature Sensor',
    temperatureSensorDesc: 'Reports air temperature near the tray and helps keep the crop in range.',
    humiditySensor: 'Humidity Sensor',
    humiditySensorDesc: 'Tracks humidity levels around the tray for plant comfort.',
    pHSensor: 'pH Sensor',
    pHSensorDesc: 'Monitors nutrient solution acidity for healthy root uptake.',
    waterFlowSensor: 'Water Flow Sensor',
    waterFlowSensorDesc: 'Measures irrigation flow rate and water usage from the tray.',
    sensorOverview: 'Sensor Overview',
    connectedDevice: 'Connected',
    noSensorData: 'No sensor data available.',
    optimalRange: 'Optimal Range',
    sensorCurrentTray: 'Current tray: {trayId} — {cropName}',
    viewSensorGraph: 'View sensor graph',
    sensorTrendHistory: 'Sensor trend history',
    graphNoData: 'No history yet for this sensor. Waiting for live data.',
    selectedTray: 'Selected Tray',
    latestReading: 'Latest reading',
    lowest: 'Lowest',
    highest: 'Highest',
    dataPoints: 'Data points',
    selectSensorLabel: 'Select sensor',
    mlPerMinute: 'ml/min',
    loading: 'Loading...',
    statusHealthy: 'Healthy',
    usingRealTrayHistory: 'Using real tray history for predictions.',
    usingFallbackSensorData: 'Using fallback sensor data for predictions.',
    aiChat: 'AI Assistant',
    aiChatTitle: 'AI Farm Assistant',
    aiChatDescription: 'Ask questions about your AI recommendations and farm data to improve your vertical farm.',
    quickSuggestionsLabel: 'Quick Suggestions',
    startChatting: 'Start Chatting with Your AI Assistant',
    askAboutRecommendations: 'Ask about your AI recommendations, sensor data, or ways to improve your farm.',
    askAQuestion: 'Ask a question about your farm...',
    sending: 'Sending...',
    send: 'Send',
    aiChatFooter: 'AI responses are based on your current farm data and recommendations.',
  },
  zh: {
    dashboard: '仪表板',
    settings: '设置',
    logout: '登出',
    signIn: '登录',
    signUp: '创建账号',
    signupHeading: '创建您的账户',
    loginSubheading: '智能农业平台',
    emailAddress: '电子邮件地址',
    password: '密码',
    fullName: '全名',
    confirmPassword: '确认密码',
    minPasswordChars: '至少 6 个字符',
    noAccount: '还没有账号？',
    alreadyHaveAccount: '已有账号？',
    createOne: '创建一个',
    signInLink: '登录',
    bySigningUp: '注册即表示您同意我们的服务条款和隐私政策',
    freeAccount: '免费账户',
    instantSetup: '即时设置',
    fullFeatures: '完整功能',
    language: '语言',
    languageName: '中文',
    pleaseFillFields: '请填写所有字段',
    invalidEmail: '无效的电子邮件地址',
    noAccountFound: '未找到该电子邮件的账户',
    incorrectPassword: '密码错误',
    emailAlreadyInUse: '电子邮件已被使用',
    weakPassword: '密码太弱',
    passwordsDoNotMatch: '两次密码输入不匹配',
    nameAtLeast2Chars: '姓名必须至少 2 个字符',
    passwordAtLeast6Chars: '密码必须至少 6 个字符',
    failedToSignIn: '登录失败',
    failedToCreateAccount: '创建账户失败',
    signingIn: '正在登录...',
    creatingAccount: '正在创建账户...',
    realTimeMonitoring: '实时监控',
    aiInsights: 'AI 见解',
    smartControls: '智能控制',
    emailPlaceholder: 'your.email@company.com',
    passwordPlaceholder: '输入您的密码',
    confirmPasswordPlaceholder: '••••••••',
    dashboardOverview: '实时监控所有托盘和系统状态',
    activeTrays: '活动托盘',
    averageHealth: '平均健康',
    activeAlerts: '活动警报',
    lastUpdate: '最后更新',
    traysCurrentlyOnline: '当前在线托盘',
    averageAIScore: '托盘平均 AI 得分',
    openSystemNotifications: '打开系统通知',
    mostRecentSensorData: '最新传感器数据',
    quickActions: '快捷操作',
    jumpIntoWorkflows: '快速进入关键 Farmsense 工作流程。',
    manageTrays: '管理托盘',
    viewAnalytics: '查看分析',
    mlInsights: 'ML 见解',
    systemSettings: '系统设置',
    howToUseFarmsense: '如何使用 Farmsense',
    assignYourTrays: '在托盘管理中为您的托盘分配作物。',
    monitorLiveConditions: '在仪表板上监控实时状况和警报。',
    trackTrends: '在分析中跟踪趋势和性能。',
    reviewAIInsights: '在 ML 见解中查看 AI 建议。',
    adjustPreferences: '在设置中调整偏好。',
    recentAlerts: '最近警报',
    aiDrivenInsights: 'AI 驱动见解',
    exploreMLInsights: '探索 ML 见解',
    goToMLInsights: '前往 ML 见解',
    trayStatus: '托盘状态',
    trayDetails: '托盘 {trayId} 详情',
    waitingForSensorData: '等待传感器数据...',
    liveSensorReadings: '实时传感器读取',
    cropLabel: '作物',
    statusLabel: '状态',
    aiScoreLabel: 'AI 得分',
    testControls: '测试控制',
    simulateTempAnomaly: '模拟温度异常',
    simulateHumidityAnomaly: '模拟湿度异常',
    assign: '分配',
    cancel: '取消',
    selectCropPlaceholder: '选择一种作物...',
    trayManagement: '托盘管理',
    assignCropsDescription: '将作物分配给托盘并监控参数',
    yourTrays: '您的托盘',
    cropProfiles: '作物配置文件',
    systemControlsLabel: '系统控制',
    turnOnLED: '打开 LED',
    turnOnAC: '打开 AC',
    startIrrigation: '开始灌溉',
    analyticsAndTrends: '分析与趋势',
    monitorSensorTrends: '监控传感器趋势和历史数据',
    selectTrayLabel: '选择托盘',
    timeRangeLabel: '时间范围',
    last1Hour: '过去1小时',
    last6Hours: '过去6小时',
    last12Hours: '过去12小时',
    last24Hours: '过去24小时',
    last7Days: '过去7天',
    currentReadingsHeading: '当前读取',
    yieldForecastHeading: '产量预测',
    harvestProjectionHeading: '收获预测',
    usingRealSensorHistory: '使用真实传感历史进行预测。',
    usingFallbackTrendData: '使用备用趋势数据进行预测。',
    temperatureTrend: '温度趋势',
    humidityTrend: '湿度趋势',
    pHTrend: 'pH 值趋势',
    waterUsageTrend: '用水趋势',
    noData: '无数据',
    liveSensorReadings: '实时传感器读取',
    temperature: '温度',
    humidity: '湿度',
    score: '得分',
    phLevel: 'pH 水平',
    lightHours: '光照小时',
    assignToTray: '分配到托盘',
    confidence: '置信度',
    trendLabel: '趋势',
    daysToHarvest: '收获天数',
    estimatedDate: '预计日期',
    tbd: '待定',
    optimalParametersFor: '{cropName} 的最佳参数',
    maturity: '成熟度',
    estimatedYield: '预计产量',
    harvestReadiness: '收获准备度',
    aiPoweredPredictions: '用于最佳农业的 AI 预测',
    noTraySelected: '未选择托盘',
    realTrayHistory: '真实托盘历史',
    fallbackSensorData: '备用传感器数据',
    efficiencyScore: '效率得分',
    days: '天',
    growStageLabel: '生长阶段',
    vegetative: '营养生长',
    flowering: '开花',
    fruiting: '结果',
    daysSincePlanted: '种植天数',
    healthy: '健康',
    yieldPredictionTitle: '产量预测',
    harvestPredictionTitle: '收获预测',
    nutrientRequirements: '营养需求',
    waterConsumptionForecast: '用水预测',
    predictedDailyUsage: '预计每日用量',
    adjustmentFactors: '调整因素',
    adjustmentLabel: '调整',
    reasonLabel: '原因',
    resourceEfficiency: '资源效率',
    anomalyDetection: '异常检测',
    riskLevelLabel: '风险等级',
    noAnomaliesDetected: '✅ 未检测到异常。系统正常运行。',
    systemOperatingNormally: '系统正常运行。',
    configureSystem: '配置您的 Farmsense 系统',
    accountSettings: '账户设置',
    notificationsHeading: '通知',
    criticalAlerts: '关键警报',
    dailyReports: '每日报告',
    marketingEmails: '营销邮件',
    dataRefreshInterval: '数据刷新间隔（秒）',
    alertSensitivity: '警报灵敏度',
    low: '低',
    medium: '中',
    high: '高',
    saveSettings: '保存设置',
    dangerZone: '危险区域',
    deleteAccount: '删除账户',
    update: '更新',
    emailLabel: '电子邮件',
    passwordLabel: '密码',
    selectCrop: '选择一种作物...',
    tray: '托盘',
    trayLabel: '托盘',
    unassigned: '未分配',
    onlineStatus: '🟢 在线',
    offlineStatus: '🔴 离线',
    loading: '加载中...',
    statusHealthy: '健康',
    usingRealTrayHistory: '使用真实托盘历史进行预测。',
    usingFallbackSensorData: '使用备用传感数据进行预测。',
    aiChat: 'AI 助手',
    aiChatTitle: 'AI 农场助手',
    aiChatDescription: '询问有关您的 AI 建议和农场数据的问题，以改进您的竖直农场。',
    quickSuggestionsLabel: '快速建议',
    startChatting: '开始与您的 AI 助手聊天',
    askAboutRecommendations: '询问您的 AI 建议、传感器数据或改进农场的方法。',
    askAQuestion: '询问有关您的农场的问题...',
    sending: '发送中...',
    send: '发送',
    aiChatFooter: 'AI 回复基于您当前的农场数据和建议。',
  },
  bm: {
    dashboard: 'Papan Pemuka',
    settings: 'Tetapan',
    logout: 'Log keluar',
    signIn: 'Log Masuk',
    signUp: 'Buat Akaun',
    signupHeading: 'Buat Akaun Anda',
    loginSubheading: 'Platform Pertanian Pintar',
    emailAddress: 'Alamat Emel',
    password: 'Kata Laluan',
    fullName: 'Nama Penuh',
    confirmPassword: 'Sahkan Kata Laluan',
    minPasswordChars: 'Min. 6 aksara',
    noAccount: 'Tiada akaun?',
    alreadyHaveAccount: 'Sudah ada akaun?',
    createOne: 'Buat satu',
    signInLink: 'Log masuk',
    bySigningUp: 'Dengan mendaftar, anda bersetuju dengan Terma Perkhidmatan dan Dasar Privasi kami',
    freeAccount: 'Akaun percuma',
    instantSetup: 'Persediaan segera',
    fullFeatures: 'Ciri penuh',
    language: 'Bahasa',
    languageName: 'BM',
    pleaseFillFields: 'Sila isi semua medan',
    invalidEmail: 'Alamat emel tidak sah',
    noAccountFound: 'Tiada akaun ditemui dengan emel ini',
    incorrectPassword: 'Kata laluan salah',
    emailAlreadyInUse: 'Emel sudah digunakan',
    weakPassword: 'Kata laluan terlalu lemah',
    passwordsDoNotMatch: 'Kata laluan tidak sepadan',
    nameAtLeast2Chars: 'Nama mesti sekurang-kurangnya 2 aksara',
    passwordAtLeast6Chars: 'Kata laluan mesti sekurang-kurangnya 6 aksara',
    failedToSignIn: 'Gagal log masuk',
    failedToCreateAccount: 'Gagal membuat akaun',
    signingIn: 'Sedang log masuk...',
    creatingAccount: 'Sedang membuat akaun...',
    realTimeMonitoring: 'Pemantauan masa nyata',
    aiInsights: 'Gambaran AI',
    smartControls: 'Kawalan pintar',
    emailPlaceholder: 'your.email@company.com',
    passwordPlaceholder: 'Masukkan kata laluan anda',
    confirmPasswordPlaceholder: '••••••••',
    dashboardOverview: 'Pemantauan masa nyata semua tray dan kesihatan sistem',
    activeTrays: 'Tray Aktif',
    averageHealth: 'Kesihatan Purata',
    activeAlerts: 'Amaran Aktif',
    lastUpdate: 'Kemas kini Terakhir',
    traysCurrentlyOnline: 'Tray dalam talian sekarang',
    averageAIScore: 'Skor AI purata merentas tray',
    openSystemNotifications: 'Notifikasi sistem terbuka',
    mostRecentSensorData: 'Data sensor terkini',
    quickActions: 'Tindakan Pantas',
    jumpIntoWorkflows: 'Terus ke aliran kerja Farmsense utama.',
    manageTrays: 'Urus Tray',
    viewAnalytics: 'Lihat Analitik',
    mlInsights: 'Wawasan ML',
    systemSettings: 'Tetapan Sistem',
    howToUseFarmsense: 'Cara Menggunakan Farmsense',
    assignYourTrays: 'Tetapkan tanaman ke dalam tray dan pantau parameter.',
    monitorLiveConditions: 'Pantau keadaan langsung dan amaran di papan pemuka.',
    trackTrends: 'Jejaki trend dan prestasi dalam Analitik.',
    reviewAIInsights: 'Semak wawasan AI dalam ML Insights.',
    adjustPreferences: 'Laraskan pilihan dalam Tetapan.',
    recentAlerts: 'Amaran Terkini',
    aiDrivenInsights: 'Wawasan dipacu AI',
    exploreMLInsights: 'Terokai ML Insights',
    goToMLInsights: 'Pergi ke ML Insights',
    trayStatus: 'Status Tray',
    trayDetails: 'Butiran Tray {trayId}',
    waitingForSensorData: 'Menunggu data sensor...',
    liveSensorReadings: 'Pembacaan Sensor Langsung',
    cropLabel: 'Tanaman',
    statusLabel: 'Status',
    aiScoreLabel: 'Skor AI',
    testControls: 'Kawalan Ujian',
    simulateTempAnomaly: 'Mensimulasikan Anomali Suhu',
    simulateHumidityAnomaly: 'Mensimulasikan Anomali Kelembapan',
    assign: 'Tetapkan',
    cancel: 'Batal',
    selectCropPlaceholder: 'Pilih tanaman...',
    trayManagement: 'Pengurusan Tray',
    assignCropsDescription: 'Tetapkan tanaman ke tray dan pantau parameter',
    yourTrays: 'Tray Anda',
    cropProfiles: 'Profil Tanaman',
    systemControlsLabel: 'Kawalan Sistem',
    turnOnLED: 'Hidupkan LED',
    turnOnAC: 'Hidupkan AC',
    startIrrigation: 'Mula Pengairan',
    analyticsAndTrends: 'Analitik & Trend',
    monitorSensorTrends: 'Pantau trend sensor dan data sejarah',
    selectTrayLabel: 'Pilih Tray',
    timeRangeLabel: 'Julat Masa',
    last1Hour: '1 Jam Terakhir',
    last6Hours: '6 Jam Terakhir',
    last12Hours: '12 Jam Terakhir',
    last24Hours: '24 Jam Terakhir',
    last7Days: '7 Hari Terakhir',
    currentReadingsHeading: 'Pembacaan Semasa',
    yieldForecastHeading: 'Ramalan Hasil',
    harvestProjectionHeading: 'Unjuran Tuai',
    usingRealSensorHistory: 'Menggunakan sejarah sensor sebenar untuk ramalan.',
    usingFallbackTrendData: 'Menggunakan data trend gantian untuk ramalan.',
    temperatureTrend: 'Trend Suhu',
    humidityTrend: 'Trend Kelembapan',
    pHTrend: 'Trend Tahap pH',
    waterUsageTrend: 'Trend Penggunaan Air',
    noData: 'Tiada data',
    liveSensorReadings: 'Pembacaan Sensor Langsung',
    temperature: 'Suhu',
    humidity: 'Kelembapan',
    score: 'Skor',
    phLevel: 'Tahap pH',
    lightHours: 'Jam Cahaya',
    assignToTray: 'Tetapkan ke Tray',
    confidence: 'Keyakinan',
    trendLabel: 'Trend',
    daysToHarvest: 'Hari ke Tuai',
    estimatedDate: 'Tarikh Anggaran',
    tbd: 'TBD',
    optimalParametersFor: 'Parameter Optimum untuk {cropName}',
    maturity: 'Matang',
    estimatedYield: 'Hasil Dianggarkan',
    harvestReadiness: 'Kesediaan Tuai',
    aiPoweredPredictions: 'Ramalan AI untuk pertanian terbaik',
    noTraySelected: 'Tiada tray dipilih',
    realTrayHistory: 'sejarah tray nyata',
    fallbackSensorData: 'data sensor gantian',
    efficiencyScore: 'Skor Kecekapan',
    days: 'hari',
    growStageLabel: 'Peringkat Pertumbuhan',
    vegetative: 'Vegetatif',
    flowering: 'Berbunga',
    fruiting: 'Berbuah',
    daysSincePlanted: 'Hari Sejak Ditanam',
    healthy: 'Sihat',
    yieldPredictionTitle: 'Ramalan Hasil',
    harvestPredictionTitle: 'Ramalan Tuai',
    nutrientRequirements: 'Keperluan Nutrien',
    waterConsumptionForecast: 'Ramalan Penggunaan Air',
    predictedDailyUsage: 'Penggunaan Harian Dijangka',
    adjustmentFactors: 'Faktor Pelarasan',
    adjustmentLabel: 'Pelarasan',
    reasonLabel: 'Sebab',
    resourceEfficiency: 'Kecekapan Sumber',
    anomalyDetection: 'Pengesanan Anomali',
    riskLevelLabel: 'Tahap Risiko',
    noAnomaliesDetected: '✅ Tiada anomali dikesan. Sistem beroperasi dengan normal.',
    systemOperatingNormally: 'Sistem beroperasi dengan normal.',
    configureSystem: 'Konfigurasikan sistem Farmsense anda',
    accountSettings: 'Tetapan Akaun',
    notificationsHeading: 'Pemberitahuan',
    criticalAlerts: 'Amaran Kritikal',
    dailyReports: 'Laporan Harian',
    marketingEmails: 'E-mel Pemasaran',
    dataRefreshInterval: 'Selang Segar Data (saat)',
    alertSensitivity: 'Sensitiviti Amaran',
    low: 'Rendah',
    medium: 'Sederhana',
    high: 'Tinggi',
    saveSettings: 'Simpan Tetapan',
    dangerZone: 'Zon Bahaya',
    deleteAccount: 'Padam Akaun',
    update: 'Kemas kini',
    emailLabel: 'Emel',
    passwordLabel: 'Kata Laluan',
    selectCrop: 'Pilih tanaman...',
    tray: 'Tray',
    trayLabel: 'Tray',
    unassigned: 'Belum ditugaskan',
    onlineStatus: '🟢 Dalam talian',
    offlineStatus: '🔴 Luar talian',
    loading: 'Memuat...',
    statusHealthy: 'Sihat',
    usingRealTrayHistory: 'Menggunakan sejarah tray sebenar untuk ramalan.',
    usingFallbackSensorData: 'Menggunakan data sensor gantian untuk ramalan.',
  },
  ta: {
    dashboard: 'அட்டைப்படி',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    signIn: 'உள் நுழை',
    signUp: 'கணக்கு உருவாக்கு',
    signupHeading: 'உங்கள் கணக்கை உருவாக்கவும்',
    loginSubheading: 'ஸ்மார்ட் வேளாண் தளம்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    fullName: 'முழுப்பெயர்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    minPasswordChars: 'குறைந்தபட்சம் 6 எழுத்துக்கள்',
    noAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே ஒரு கணக்கு உள்ளதா?',
    createOne: 'உருவாக்கவும்',
    signInLink: 'உள் நுழைய',
    bySigningUp: 'பதிவு செய்வதன் மூலம், நீங்கள் எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்',
    freeAccount: 'இலவச கணக்கு',
    instantSetup: 'உடனடி அமைப்பு',
    fullFeatures: 'முழு அம்சங்கள்',
    language: 'மொழி',
    languageName: 'தமிழ்',
    pleaseFillFields: 'தயவுசெய்து அனைத்து புலங்களையும் நிரப்பவும்',
    invalidEmail: 'தவறான மின்னஞ்சல் முகவரி',
    noAccountFound: 'இந்த மின்னஞ்சலுடன் எந்த கணக்கும் கிடையாது',
    incorrectPassword: 'தவறான கடவுச்சொல்',
    emailAlreadyInUse: 'மின்னஞ்சல் ஏற்கனவே பயன்படுத்தப்படுகிறது',
    weakPassword: 'கடவுச்சொல் பலமற்றது',
    passwordsDoNotMatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    nameAtLeast2Chars: 'பெயர் குறைந்தது 2 எழுத்துக்களாக இருக்க வேண்டும்',
    passwordAtLeast6Chars: 'கடவுச்சொல் குறைந்தபட்சம் 6 எழுத்துகள் இருக்க வேண்டும்',
    failedToSignIn: 'உள் நுழைவு தோல்வியடைந்தது',
    failedToCreateAccount: 'கணக்கு உருவாக்கம் தோல்வியடைந்தது',
    signingIn: 'உள் நுழைகிறது...',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    realTimeMonitoring: 'உண்மையான நேர கண்காணிப்பு',
    aiInsights: 'AI பார்வைகள்',
    smartControls: 'அறிவூட்டிய கட்டுப்பாடுகள்',
    emailPlaceholder: 'your.email@company.com',
    passwordPlaceholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    confirmPasswordPlaceholder: '••••••••',
    dashboardOverview: 'அனைத்து ட்ரேங்களையும் மற்றும் அமைப்பு நலத்தையும் நேரடியாக கண்காணிக்கவும்',
    activeTrays: 'செயலில் உள்ள ட்ரேக்கள்',
    averageHealth: 'சராசரி நலம்',
    activeAlerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    lastUpdate: 'இறுதி புதுப்பிப்பு',
    traysCurrentlyOnline: 'தற்போது ஆன்லைனில் உள்ள ட்ரேக்கள்',
    averageAIScore: 'ட்ரேக்களுக்கிடையில் சராசரி AI மதிப்பெண்',
    openSystemNotifications: 'அமைப்பு அறிவிப்புகளை திறக்கவும்',
    mostRecentSensorData: 'சமீபத்திய சென்சார் தரவு',
    quickActions: 'தோடணைகள்',
    jumpIntoWorkflows: 'முக்கிய Farmsense பணிகள் வழிகளில் தேர்வு செய்யவும்.',
    manageTrays: 'ட்ரேக்களை நிர்வகிக்கவும்',
    viewAnalytics: 'பகுப்பாய்வுகளை காண்க',
    mlInsights: 'ML பார்வைகள்',
    systemSettings: 'அமைப்பு அமைப்புகள்',
    howToUseFarmsense: 'Farmsense-ஐ எப்படி பயன்படுத்துவது',
    assignYourTrays: 'உங்கள் ட்ரேக்களுக்கு பயிர்களை ஒதுக்கவும் மற்றும் அளவுருக்களை கண்காணிக்கவும்.',
    monitorLiveConditions: 'டாஷ்போர்டில் நேரடி நிலைகளையும் எச்சரிப்புகளையும் கண்காணிக்கவும்.',
    trackTrends: 'பகுப்பாய்வில் போக்குகளையும் செயல்திறனையும் கண்காணிக்கவும்.',
    reviewAIInsights: 'ML பார்வைகளில் AI வழிகாட்டல்களை மதிப்பாய்வு செய்யவும்.',
    adjustPreferences: 'அமைப்புகளில் விருப்பங்களை மாற்றவும்.',
    recentAlerts: 'சமீபத்திய எச்சரிக்கைகள்',
    aiDrivenInsights: 'AI இயக்கப்பட்ட பார்வைகள்',
    exploreMLInsights: 'ML பார்வைகளை ஆராயவும்',
    goToMLInsights: 'ML பார்வைகளுக்கு செல்லவும்',
    trayStatus: 'ட்ரே நிலை',
    trayDetails: 'ட்ரே {trayId} விவரங்கள்',
    waitingForSensorData: 'சென்சார் தரவுக்காக காத்திருக்கிறது...',
    liveSensorReadings: 'நேரடி சென்சார் வாசிப்புகள்',
    cropLabel: 'பயிர்',
    statusLabel: 'நிலை',
    aiScoreLabel: 'AI மதிப்பெண்',
    testControls: 'சோதனை கட்டுப்பாடுகள்',
    simulateTempAnomaly: 'வெப்பச் சிப் சீற்றத்தை சிமுலேட் செய்யவும்',
    simulateHumidityAnomaly: 'ஈரப்பதச் சிப் சீற்றத்தை சிமுலேட் செய்யவும்',
    assign: 'ஒதுக்கவும்',
    cancel: 'ரத்துசெய்',
    selectCropPlaceholder: 'ஒரு பயிரைத் தேர்ந்தெடுக்கவும்...',
    trayManagement: 'ட்ரே மேலாண்மை',
    assignCropsDescription: 'ட்ரேக்களுக்கு பயிர்களை ஒதுக்கவும் மற்றும் அளவுருக்களை கண்காணிக்கவும்',
    yourTrays: 'உங்கள் ட்ரேக்கள்',
    cropProfiles: 'பயிர் சுயவிவரங்கள்',
    systemControlsLabel: 'அமைப்பு கட்டுப்பாடுகள்',
    turnOnLED: 'LED ஐ இயக்கவும்',
    turnOnAC: 'AC ஐ இயக்கவும்',
    startIrrigation: 'அரைப்பு தொடங்கவும்',
    analyticsAndTrends: 'பகுப்பாய்வு மற்றும் போக்குகள்',
    monitorSensorTrends: 'சென்சார் போக்குகளையும் வரலாற்று தரவையும் கண்காணிக்கவும்',
    selectTrayLabel: 'ட்ரே தேர்வு செய்க',
    timeRangeLabel: 'நேர வரம்பு',
    last1Hour: 'கடந்த 1 மணி நேரம்',
    last6Hours: 'கடந்த 6 மணி நேரம்',
    last12Hours: 'கடந்த 12 மணி நேரம்',
    last24Hours: 'கடந்த 24 மணி நேரம்',
    last7Days: 'கடந்த 7 நாட்கள்',
    currentReadingsHeading: 'தற்போதைய வாசிப்புகள்',
    yieldForecastHeading: 'பயிர் விளைவு முன்னறிவு',
    harvestProjectionHeading: 'வெட்டீட்டு கணிப்பு',
    usingRealSensorHistory: 'முன்னறிவுக்காக உண்மையான ட்ரே வரலாற்றைப் பயன்படுத்துகிறது.',
    usingFallbackTrendData: 'மறுசீரமைப்பு போக்குத் தரவு பயன்படுத்தப்படுகிறது.',
    temperatureTrend: 'வெப்பநிலை போக்கு',
    humidityTrend: 'ஈரப்பத போக்கு',
    pHTrend: 'pH நிலை போக்கு',
    waterUsageTrend: 'தண்ணீர் பயன்பாடு போக்கு',
    noData: 'தரவு கிடையாது',
    liveSensorReadings: 'நேரடி சென்சார் வாசிப்புகள்',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    score: 'மதிப்பெண்',
    phLevel: 'pH நிலை',
    lightHours: 'ஒளி மணித்தியாலங்கள்',
    assignToTray: 'ட்ரேக்கு ஒதுக்கவும்',
    confidence: 'நம்பிக்கை',
    trendLabel: 'போக்கு',
    daysToHarvest: 'விவசாயத்திற்கு நாட்கள்',
    estimatedDate: ' மதிப்பீட்டு தேதி',
    tbd: 'TBD',
    optimalParametersFor: '{cropName}க்கான சிறந்த அளவுருக்கள்',
    maturity: 'முழுமை',
    estimatedYield: 'மதிப்பிடப்பட்ட உற்பத்தி',
    harvestReadiness: 'விவசாயத் தயார்மை',
    aiPoweredPredictions: 'அல்லவுடையான வேளாண்மைக்கான AI முன்மொழிவுகள்',
    noTraySelected: 'ட்ரே தேர்வு செய்யப்படவில்லை',
    realTrayHistory: 'உண்மையான ட்ரே வரலாறு',
    fallbackSensorData: 'மறுசீரமைப்பு சென்சார் தரவு',
    efficiencyScore: 'திறன் மதிப்பெண்',
    days: 'நாட்கள்',
    growStageLabel: 'படரும் நிலை',
    vegetative: 'மூட்டணங்கு',
    flowering: 'மலர்ச்சி',
    fruiting: 'பழம்',
    daysSincePlanted: 'நட்டுக் கணங்கள்',
    healthy: 'ஆரோக்கியமான',
    yieldPredictionTitle: 'பயிர் முன்னறிவு',
    harvestPredictionTitle: 'வெட்டீட்டு கணிப்பு',
    nutrientRequirements: 'உணவு தேவைகள்',
    waterConsumptionForecast: 'தண்ணீர் பயன்பாட்டு கணிப்பு',
    predictedDailyUsage: 'தினசரி பயன்படுத்தும் எstimேஷன்',
    adjustmentFactors: 'சரிசெய்தல் காரணிகள்',
    adjustmentLabel: 'சரிசெய்தல்',
    reasonLabel: 'காரணம்',
    resourceEfficiency: 'வள திறன்',
    anomalyDetection: 'அசாதாரணம் கண்டறிதல்',
    riskLevelLabel: 'ஆபத்துத் தளம்',
    noAnomaliesDetected: '✅ எந்த அசாதாரணமும் கண்டறியப்படவில்லை. முறைப்பாடு சாதாரணமாக இயங்குகிறது.',
    systemOperatingNormally: 'முறைப்பாடு சாதாரணமாக இயங்குகிறது.',
    configureSystem: 'உங்கள் Farmsense அமைப்பை கட்டமைக்கவும்',
    accountSettings: 'கணக்கு அமைப்புகள்',
    notificationsHeading: 'அறிவிப்புகள்',
    criticalAlerts: 'முக்கிய எச்சரிக்கைகள்',
    dailyReports: 'தினசரி அறிக்கைகள்',
    marketingEmails: 'மார்க்கெட்டிங் மின்னஞ்சல்கள்',
    dataRefreshInterval: 'தரவு புதுப்பிப்பு இடைவேளை (விநாடிகள்)',
    alertSensitivity: 'எச்சரிக்கை உணர்வு',
    low: 'தாழ்',
    medium: 'மிதமான',
    high: 'உயர்',
    saveSettings: 'அமைப்புகளை சேமி',
    dangerZone: 'ஆபத்தான பகுதி',
    deleteAccount: 'கணக்கை அழிக்கவும்',
    update: 'புதுப்பி',
    emailLabel: 'மின்னஞ்சல்',
    passwordLabel: 'கடவுச்சொல்',
    selectCrop: 'ஒரு பயிரைத் தேர்ந்தெடுக்கவும்...',
    hardwareSensorSection: 'ஹார்ட்வேர் சென்சார் இடைமுகம்',
    hardwareSensorHoverDescription: 'தேர்ந்தெடுக்கப்பட்ட ட்ரேயின் நேரடி தரவைச் காண சென்சார் மீது ஹோவர் செய்யவும்.',
    arduinoSensor: 'அர்டினோ பலகை',
    arduinoSensorDesc: 'எல்லா ட்ரே சென்சார் படிகளைப் பாகுபடுத்தும் முக்கிய கட்டுப்பாட்டு பலகை.',
    temperatureSensor: 'வெப்பநிலை சென்சார்',
    temperatureSensorDesc: 'ட்ரே அருகிலுள்ள காற்று வெப்பநிலையைப் பதிவு செய்யிறது.',
    humiditySensor: ' ஈரமான நிலை சென்சார்',
    humiditySensorDesc: 'ட்ரே சுற்றியுள்ள ஈரப்பதத்தை கண்காணிக்கிறது.',
    pHSensor: 'pH சென்சார்',
    pHSensorDesc: 'மூலப்பொருள் நீரில் அமிலத்தன்மையை கண்காணிக்கிறது.',
    waterFlowSensor: 'தண்ணீர் ஓட்ட சென்சார்',
    waterFlowSensorDesc: 'இர்ரிகேஷன் ஓட்ட விகிதத்தை மற்றும் நீர் பயன்பாட்டை அளக்கிறது.',
    sensorOverview: 'சென்சார் கண்ணோட்டம்',
    connectedDevice: 'இணைக்கப்பட்டது',
    noSensorData: 'சென்சார் தரவு கிடைக்கவில்லை.',
    optimalRange: 'உகந்த வரம்பு',
    sensorCurrentTray: 'தற்போதைய ட்ரே: {trayId} — {cropName}',
    mlPerMinute: 'மி.லீ./நிமிடம்',
    trayLabel: 'டிரே',
    unassigned: 'ஒதுக்கப்படவில்லை',
    onlineStatus: '🟢 ஆன்லைன்',
    offlineStatus: '🔴 ஆஃப்லைன்',
    loading: 'ஏற்றுகிறது...',
    tray: 'ட்ரே',
    statusHealthy: 'ஆரோக்கியமான',
    usingRealTrayHistory: 'முன்னறிவுக்கு உண்மையான ட்ரே வரலாற்றைப் பயன்படுத்துகிறது.',
    usingFallbackSensorData: 'மறுசீரமைப்பு சென்சார் தரவு பயன்படுத்தப்படுகிறது.',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('farmsense_language');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (newLanguage) => {
    if (!translations[newLanguage]) return;
    setLanguage(newLanguage);
    localStorage.setItem('farmsense_language', newLanguage);
  };

  const t = (key, vars) => {
    const translation = translations[language]?.[key] || translations.en[key] || key;
    if (!vars) return translation;
    return Object.keys(vars).reduce((text, varKey) => text.replace(new RegExp(`\{${varKey}\}`, 'g'), vars[varKey]), translation);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};